### ISSUE TITLE
Interfaz minimalista 

### ISSUE THREAD

**Issue by IvanMass99** [PPROF1-2021/g9-objetivospersonales#8]
Realizar un diseño de interfaz sencillo y amigable para el usuario.

> Sugerencias / ideas:

[Imagen 1](https://dribbble.com/shots/11672842-API-Website)

[Imagen 2](https://dribbble.com/shots/14012516-Landing-Page-Paulini)

> Diseño en progreso:

[Imagen 1](https://drive.google.com/file/d/1ek3h6GQNc50LnIA3z69nqONXECgtg-nl/view?usp=sharing)

**Comment by ShadyG98** [comment]
Finalizado por Ivan y Juan con los toques finales!!
